name: CI

on: [pull_request, push]    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.3
          - 27.1
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
       version: ${{ matrix.emacs_version }}
    - name: Install cask
      run: git clone --depth=1 https://github.com/cask/cask.git "${HOME}/.cask" && sudo ln -s "${HOME}/.cask/bin/cask" "/usr/local/bin/cask"
    - uses: actions/checkout@v1
    - name: Run tests
      run: make setup test
